### ISSUE TITLE
warc-explorer-dist/1.0.0/warc-explorer-dist-1.0.0-bin.zip not found

### ISSUE THREAD

**Issue by jvw1954** [ukwa/webarchive-explorer#7]
The link _Download: warc-explorer-dist-1.0.0-bin.zip_ [http://repo2.maven.org/maven2/uk/bl/wa/warc-explorer/warc-explorer-dist/1.0.0/warc-explorer-dist-1.0.0-bin.zip](http://repo2.maven.org/maven2/uk/bl/wa/warc-explorer/warc-explorer-dist/1.0.0/warc-explorer-dist-1.0.0-bin.zip) gives an **not found** error.

**Comment by anjackson** [comment]
I've updated the link to https://search.maven.org/remotecontent?filepath=uk/bl/wa/warc-explorer/warc-explorer-dist/1.0.0/warc-explorer-dist-1.0.0-bin.zip

But I would say this was an old experiment that we're unlikely to return to.  I would recommend trying the WebReplay.Page App (see https://github.com/webrecorder/replayweb.page and associated releases).
